import { PRODUCT_CONTROLLER } from '../controllers/products';
import { Router } from 'express';

const PRODUCT_ROUTER = Router();

PRODUCT_ROUTER.get('/', PRODUCT_CONTROLLER.GET_ALL);
PRODUCT_ROUTER.get('/:id', PRODUCT_CONTROLLER.GET_BY_ID);
PRODUCT_ROUTER.post('/', PRODUCT_CONTROLLER.CREATE);
PRODUCT_ROUTER.put('/:id', PRODUCT_CONTROLLER.UPDATE);
PRODUCT_ROUTER.delete('/:id', PRODUCT_CONTROLLER.DELETE);
PRODUCT_ROUTER.post('/:id/like', PRODUCT_CONTROLLER.LIKE);
PRODUCT_ROUTER.post('/:id/dislike', PRODUCT_CONTROLLER.DISLIKE);

export default PRODUCT_ROUTER;